name: 🔎 Lint

on:
    workflow_dispatch:
    push:
        branches-ignore: [gh-pages]
    pull_request:
        branches-ignore: [gh-pages]
        types: [opened, synchronize]

permissions:
    contents: read

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

env:
    HUSKY: '0'

jobs:
    build:
        name: 🔨 Build
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: yarn

            - name: ⚡ Install dependencies
              run: yarn install --frozen-lockfile

            - name: 🔨 Build
              run: yarn build:lib

    test:
        name: 🧪 Test
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: yarn

            - name: ⚡ Install dependencies
              run: yarn install --frozen-lockfile

            - name: 🧪 Test
              run: yarn test:coverage

    lint:
        name: 🔎 Lint
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: yarn

            - name: ⚡ Install dependencies
              run: yarn install --frozen-lockfile

            - name: 🔎 Lint
              run: yarn lint
